# Generated by Django 4.2.28 on 2026-03-15 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_age_customuser_user_hight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_hight',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_height',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(220)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_weight',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
