# Generated by Django 4.2.28 on 2026-03-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_user_hight_customuser_user_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='male',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=20),
        ),
    ]
