# Generated by Django 4.2.28 on 2026-05-16 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0003_exercise_progression_delta_and_more'),
        ('analytics', '0002_userworkoutprogress_userprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciseprogress',
            unique_together={('user', 'exercise')},
        ),
    ]
