# Generated by Django 4.2.28 on 2026-03-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='discription',
            new_name='description',
        ),
    ]
