# Generated by Django 4.2.28 on 2026-04-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_rename_discription_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='progression_delta',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression_frequency',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='exercise',
            name='progression_type',
            field=models.CharField(choices=[('weight', 'Увеличение веса'), ('reps', 'Увеличение повторений')], default='weight', max_length=20),
        ),
    ]
