# Generated by Django 4.2.28 on 2026-03-15 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('powerlifting', 'Пауэрлифтинг'), ('weightlifting', 'Тяжелая атлетика'), ('athletics', 'Легкая атлетика'), ('fitness', 'Фитнес'), ('crossfit', 'Кроссфит'), ('keeping_form', 'Поддержание формы')], default='keeping_form', max_length=20, verbose_name='Спортивное направление')),
                ('experience', models.CharField(choices=[('beginner', 'Начинающий'), ('middle', 'Обычно'), ('pro', 'Опытный')], default='beginner', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('weeks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_number', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.trainingprogram')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('rest_time', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programexercise', to='programs.programworkout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
